# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180809_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='down_time',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
    ]
