# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-15 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resources_down_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='down_time',
        ),
    ]
