# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('jg', '监管要闻'), ('gd', '各地动态')], default='jg', max_length=10, verbose_name='投稿板块')),
            ],
            options={
                'verbose_name': '投稿板块',
                'verbose_name_plural': '投稿板块',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('plate', models.CharField(choices=[('jg', '监管要闻'), ('gd', '各地动态')], default='jg', max_length=10, verbose_name='投稿板块')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=150, verbose_name='地址')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否阅读')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
            },
        ),
    ]
