# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-12 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_submission_is_imgtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='plate',
        ),
    ]
