# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180812_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '测试模型，用完就删除',
                'verbose_name_plural': '测试模型，用完就删除',
            },
        ),
    ]
