# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-13 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180812_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSub',
        ),
    ]
