# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_delete_testsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPass',
            fields=[
            ],
            options={
                'verbose_name': '审核通过',
                'verbose_name_plural': '审核通过',
                'proxy': True,
            },
            bases=('operation.submission',),
        ),
        migrations.CreateModel(
            name='SubmissionRead',
            fields=[
            ],
            options={
                'verbose_name': '审核未通过',
                'verbose_name_plural': '审核未通过',
                'proxy': True,
            },
            bases=('operation.submission',),
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': '待审核', 'verbose_name_plural': '待审核'},
        ),
        migrations.AddField(
            model_name='submission',
            name='read_volume',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
