# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('0', '星期天')], default='1', max_length=10, verbose_name='值班星期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '值班日期',
                'verbose_name_plural': '值班日期',
            },
        ),
        migrations.CreateModel(
            name='DutyMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ld', '领导'), ('mj', '民警')], default='ld', max_length=10, verbose_name='类型')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话')),
                ('phone', models.CharField(max_length=11, verbose_name='移动手机')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.Duty', verbose_name='值班时间')),
            ],
            options={
                'verbose_name': '值班人',
                'verbose_name_plural': '值班人',
            },
        ),
    ]
