# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-10 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期天')], default=0, verbose_name='值班星期')),
                ('leader', models.CharField(max_length=10, verbose_name='领导')),
                ('leader_phone', models.CharField(max_length=11, verbose_name='移动手机')),
                ('follower', models.CharField(max_length=10, verbose_name='民警')),
                ('telephone', models.CharField(max_length=11, verbose_name='值班电话')),
                ('follower_phone', models.CharField(max_length=11, verbose_name='移动手机')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '值班人',
                'verbose_name_plural': '值班人',
            },
        ),
    ]
