# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-01 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='week',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (0, '星期天')], default=1, verbose_name='值班星期'),
        ),
    ]
