# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_auto_20180801_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyman',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='值班电话'),
        ),
    ]
