# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_volume', models.IntegerField(default=0, verbose_name='阅读量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '通知通告',
                'verbose_name_plural': '通知通告',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_volume', models.IntegerField(default=0, verbose_name='阅读量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '法律法规',
                'verbose_name_plural': '法律法规',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_volume', models.IntegerField(default=0, verbose_name='阅读量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '公示公告',
                'verbose_name_plural': '公示公告',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='文章来源')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章来源',
                'verbose_name_plural': '文章来源',
            },
        ),
        migrations.CreateModel(
            name='SpecialWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('data', models.IntegerField(verbose_name='事件数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专项工作',
                'verbose_name_plural': '专项工作',
            },
        ),
        migrations.CreateModel(
            name='TeamSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_volume', models.IntegerField(default=0, verbose_name='阅读量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源')),
            ],
            options={
                'verbose_name': '支队制度',
                'verbose_name_plural': '支队制度',
            },
        ),
        migrations.CreateModel(
            name='WorkBulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('read_volume', models.IntegerField(default=0, verbose_name='阅读量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源')),
            ],
            options={
                'verbose_name': '工作简报',
                'verbose_name_plural': '工作简报',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源'),
        ),
        migrations.AddField(
            model_name='laws',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源'),
        ),
    ]
