# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_notice_is_imgtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_imgText',
            field=models.BooleanField(default=False, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='laws',
            name='is_imgText',
            field=models.BooleanField(default=False, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='teamsystem',
            name='is_imgText',
            field=models.BooleanField(default=False, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='workbulletin',
            name='is_imgText',
            field=models.BooleanField(default=False, verbose_name='是否是图文'),
        ),
    ]
