# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-21 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180821_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='title',
            new_name='name',
        ),
    ]
