# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-10 10:13
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180728_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='laws',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='teamsystem',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='workbulletin',
            name='is_imgText',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='teamsystem',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='workbulletin',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
