# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildwork',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='helpnews',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='placesnews',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='teamnews',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
        migrations.AddField(
            model_name='videopatrol',
            name='is_imgText',
            field=models.BooleanField(default=True, verbose_name='是否是图文'),
        ),
    ]
