# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180728_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='introduce',
            field=models.CharField(default='', max_length=50, verbose_name='简介'),
        ),
    ]
