# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-09 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_introduce'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerNews',
            fields=[
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'proxy': True,
            },
            bases=('news.news',),
        ),
    ]
