# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-10 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_bannernews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildwork',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='helpnews',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='placesnews',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='teamnews',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='videopatrol',
            name='is_imgText',
        ),
    ]
