# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180810_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(default=1, verbose_name='标记')),
                ('index_click', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '首页访问量',
                'verbose_name_plural': '首页访问量',
            },
        ),
    ]
