# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180728_1128'),
        ('communication', '0002_auto_20180728_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygarden',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Source', verbose_name='文章来源'),
            preserve_default=False,
        ),
    ]
