# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-10 10:17
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180728_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='is_imgText',
        ),
        migrations.RemoveField(
            model_name='studygarden',
            name='is_imgText',
        ),
        migrations.AlterField(
            model_name='communication',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='studygarden',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
