# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-21 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期天')], default=0, verbose_name='值班星期')),
                ('detachment', models.CharField(max_length=20, verbose_name='支队')),
                ('leader_name', models.CharField(max_length=15, verbose_name='领导')),
                ('leader_phone', models.CharField(max_length=11, verbose_name='移动手机')),
                ('follower', models.CharField(max_length=10, verbose_name='民警')),
                ('follower_phone', models.CharField(max_length=11, verbose_name='移动手机')),
                ('telephone', models.CharField(max_length=11, verbose_name='值班电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '值日表',
                'verbose_name_plural': '值日表',
            },
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m', verbose_name='Logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='MovieWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='window/%Y/%m', verbose_name='Logo')),
                ('is_window', models.BooleanField(default=True, verbose_name='是否开启飘窗')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '飘窗',
                'verbose_name_plural': '飘窗',
            },
        ),
        migrations.CreateModel(
            name='OtherConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('url', models.URLField(verbose_name='访问连接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '各所链接',
                'verbose_name_plural': '各所链接',
            },
        ),
    ]
