# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-02 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_moviewindow_is_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('url', models.URLField(verbose_name='访问连接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '各所链接',
                'verbose_name_plural': '各所链接',
            },
        ),
    ]
