# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-09 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_otherconnections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviewindow',
            name='is_window',
        ),
    ]
