# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_auto_20180815_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='detachment',
            field=models.CharField(default=' ', max_length=20, verbose_name='支队'),
            preserve_default=False,
        ),
    ]
